name: edinburgh-bike-counter
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.8.*
  - jupyter=1.0.*
  - matplotlib=3.1.*
  - pandas=0.25.*
  - pip=19.3.*
  - python=3.7.*
  - requests=2.22.*
